// core headers (real sub-directory paths; the flattened <SARibbonCore/X.h>
// form exists only in the build-tree sync dir / install tree)
#include "../../src/core/SARibbonCoreGlobal.h"
#include "../../src/core/SARibbonQt5Compat.hpp"
#include "../../src/core/SARibbonEnums.h"
#include "../../src/core/SARibbonCoreUtil.h"
#include "../../src/core/SARibbonThemePalette.h"
#include "../../src/core/SARibbonThemeData.h"
#include "../../src/core/SARibbonMetrics.h"
#include "../../src/core/SARibbonAbstractLayoutItem.h"
#include "../../src/core/SARibbonAbstractLayoutHost.h"
#include "../../src/core/SARibbonCustomizeRecord.h"
#include "../../src/core/SARibbonCustomizeXml.h"
#include "../../src/core/SARibbonElementFactoryInterface.h"
#include "../../src/core/SARibbonPanelLayoutEngine.h"
#include "../../src/core/SARibbonCategoryLayoutEngine.h"
#include "../../src/core/SARibbonBarGeometryEngine.h"
#include "../../src/core/SARibbonToolButtonLayout.h"