name: Deploy Doxygen Docs to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

    - name: Generate docs
      run: |
        mkdir -p ../_site
        cd doc
        doxygen Doxyfile-wiki-cn || exit 1
        cd ..
        # 确保 .nojekyll 文件在 _site 根目录或 docs 目录中
        # 放在 _site 根目录通常就足够了，但也可以放在 docs 目录里
        touch _site/.nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages